export type Language = 'en' | 'es';
export const PORTFOLIO = {
  en: [
    {
      title: "GymApp iOS 🏋️‍♂️",
      problem: "Membership and service management for gyms.",
      solution: "Complete experience for users and admins with SwiftUI & Auth0.",
      tech: "Swift, SwiftUI, Combine, Auth0",
      result: "Smart access & 60% time reduction",
      image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop",
      repoUrl: "https://github.com/bryanvrgsc/GymApp",
      screenshots: [
        "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1616348436168-de43ad0db179?q=80&w=1381&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?q=80&w=1469&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Secure Login with Auth0",
          "User Profile with membership status",
          "Temporary Access QR",
          "Service and routine visualization"
        ],
        upcomingFeatures: [
          "Discord-style badge system for active members",
          "Entry/Exit logs (Attendance Calendar)",
          "Real-time gym occupancy visualization",
          "Equipment/Activity preference system"
        ]
      }
    },
    {
      title: "Data Warehouse for Grief Support Foundation 🗄️",
      problem: "Inefficient management of large amounts of data generated by the foundation.",
      solution: "Multidimensional Data Warehouse implementation to improve decision making and service quality.",
      tech: "SQL, ETL, PowerBI, Data Warehousing",
      result: "Integral vision & 360° impact analysis.",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1470&auto=format&fit=crop",
      presentationUrl: "docs/data_warehouse_final.pdf",
      screenshots: [
        "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1470&auto=format&fit=crop",
        "https://datablog.zeus.vision/wp-content/uploads/2017/05/datawarehouse.jpg",
        "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=1470&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Multidimensional approach (Dimensions & Measures)",
          "User & demographic data tracking",
          "Therapy session records",
          "Satisfaction surveys & key indicators"
        ],
        documents: [
            { label: "Protocol Presentation", url: "docs/data_warehouse_protocolo.pdf" },
            { label: "First Partial Presentation", url: "docs/data_warehouse_parcial1.pdf" },
            { label: "Second Partial Presentation", url: "docs/data_warehouse_parcial2.pdf" },
            { label: "Final Presentation", url: "docs/data_warehouse_final.pdf" }
        ]
      }
    },
    {
      title: "Mobile Controlled C Animation 🌐",
      problem: "3D animation project controlled remotely via mobile sensors.",
      solution: "Flutter app captures sensor data and sends it to a C server rendering in OpenGL via TCP/IP Sockets.",
      tech: "C, OpenGL, Flutter, Dart, Sockets TCP/IP",
      result: "Real-time sensor synchronization.",
      image: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?q=80&w=1470&auto=format&fit=crop",
      videoUrl: "https://youtu.be/0tyqM-I_Pr8?si=UrBlcPtQ-MtfW9RI",
      repoUrl: "https://github.com/FrancoGL20/Animacion-con-C-desde-Celular",
      screenshots: [
        "https://images.unsplash.com/photo-1617791160505-6f00504e3519?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1470&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Motion capture via Flutter sensors",
          "Real-time communication with C server via sockets",
          "3D animation rendering on computer (OpenGL)",
          "IP and port configuration for remote connection"
        ]
      }
    },
    {
      title: "iOS Online Store 🛒",
      problem: "Native e-commerce application for iOS devices.",
      solution: "Developed in Swift with a Node.js (Glitch) backend and PostgreSQL database.",
      tech: "Swift, Node.js, PostgreSQL, Glitch",
      result: "Full-stack mobile commerce.",
      image: "https://muchosnegociosrentables.com/wp-content/uploads/2020/05/monta-tu-propia-tienda-online.jpg",      repoUrl: "https://github.com/bryanvrgsc/swift_proyecto_final_apps",
      presentationUrl: "docs/ios_store_presentation.pdf",
      screenshots: [
        "https://muchosnegociosrentables.com/wp-content/uploads/2020/05/monta-tu-propia-tienda-online.jpg",
        "https://splitmetrics.com/wp-content/uploads/2017/06/apple-app-store-1-1-1024x498.png",
        "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=1470&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "User Registration",
          "Add products to shopping cart",
          "Make purchases",
          "View purchase history",
          "Review and edit user profile"
        ],
        techStack: [
            "Swift (iOS Frontend)",
            "Node.js (Backend on Glitch)",
            "PostgreSQL (ElephantSQL Database)",
            "Glitch (Hosting)"
        ]
      }
    },
    {
      title: "Appointment Scheduling App 📅",
      problem: "Multi-platform app (iOS & Android) for membership and physical access management.",
      solution: "Comprehensive solution with Flutter, Firebase, and QR attendance control.",
      tech: "Flutter, Dart, Firebase, QR Scanner",
      result: "Efficient appointment & access management.",
      image: "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1470&auto=format&fit=crop",      repoUrl: "https://github.com/bryanvrgsc/flutter_proyecto_final_apps",
      videoUrl: "https://drive.google.com/file/d/1VYnOJINVIiF5S1bowKk9b6_3pj_YH1JV/preview",
      presentationUrl: "docs/appointment_app_presentation.pdf",
      screenshots: [
        "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=1468&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?q=80&w=1374&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
           "Secure authentication with Firebase Auth",
           "Membership and service management",
           "QR code generation and scanning",
           "Attendance calendar (Entry/Exit logs)",
           "Cross-platform interface for iOS and Android"
        ],
        techStack: [
            "firebase_auth, cloud_firestore, firebase_core",
            "qr_flutter, qr_code_scanner",
            "syncfusion_flutter_calendar",
            "url_launcher"
        ]
      }
    },
    {
      title: "Predictive Analysis Scripts",
      problem: "Overstock and inefficient purchasing.",
      solution: "Python algorithms for seasonal demand prediction.",
      tech: "Python, Pandas, Scikit-learn",
      result: "25% inventory optimization.",
      image: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1470&auto=format&fit=crop",
      screenshots: [
        "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1415&auto=format&fit=crop"
      ]
    }
  ],
  es: [
    {
      title: "GymApp iOS 🏋️‍♂️",
      problem: "App para gestionar membresías y servicios de un gimnasio.",
      solution: "Experiencia completa para usuarios y administradores con SwiftUI y Auth0.",
      tech: "Swift, SwiftUI, Combine, Auth0",
      result: "Acceso inteligente y reducción de tiempos en 60%",
      image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop",
      repoUrl: "https://github.com/bryanvrgsc/GymApp",
      screenshots: [
        "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1616348436168-de43ad0db179?q=80&w=1381&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?q=80&w=1469&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Login seguro con Auth0",
          "Perfil de usuario con estado de membresía",
          "QR de acceso temporal",
          "Visualización de servicios y rutinas"
        ],
        upcomingFeatures: [
          "Sistema de badges tipo Discord para usuarios que mantienen su membresía activa",
          "Registro de entradas y salidas (Calendario de asistencias)",
          "Visualización del volumen de usuarios dentro del gimnasio en tiempo real",
          "Sistema de preferencias de equipos o actividades"
        ]
      }
    },
    {
      title: "Data Warehouse para Fundación de Acompañamiento de Duelo 🗄️",
      problem: "Gestión ineficiente de gran cantidad de datos generados por la fundación.",
      solution: "Implementación de un Data Warehouse multidimensional para mejorar la toma de decisiones y calidad de servicios.",
      tech: "SQL, ETL, PowerBI, Data Warehousing",
      result: "Visión integral y análisis de impacto 360°.",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1470&auto=format&fit=crop",
      presentationUrl: "docs/data_warehouse_final.pdf",
      screenshots: [
        "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1470&auto=format&fit=crop",
        "https://datablog.zeus.vision/wp-content/uploads/2017/05/datawarehouse.jpg",
        "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=1470&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Enfoque multidimensional (Dimensiones y medidas)",
          "Tipos de datos: Información de usuarios y demográficos",
          "Registros de sesiones de terapia",
          "Encuestas de satisfacción e indicadores clave"
        ],
        documents: [
            { label: "Presentación Protocolo", url: "docs/data_warehouse_protocolo.pdf" },
            { label: "Presentación Primer Parcial", url: "docs/data_warehouse_parcial1.pdf" },
            { label: "Presentación Segundo Parcial", url: "docs/data_warehouse_parcial2.pdf" },
            { label: "Presentación Final", url: "docs/data_warehouse_final.pdf" }
        ]
      }
    },
    {
      title: "Animación con C controlada desde celular 🌐",
      problem: "Proyecto de animación en 3D cuyo movimiento se controla desde un celular conectado a una computadora.",
      solution: "App de Flutter captura los sensores del dispositivo móvil y envía los datos al servidor en C, que renderiza la animación en tiempo real.",
      tech: "C, OpenGL, Flutter, Dart, Sockets TCP/IP",
      result: "Sincronización en tiempo real.",
      image: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?q=80&w=1470&auto=format&fit=crop",
      videoUrl: "https://youtu.be/0tyqM-I_Pr8?si=UrBlcPtQ-MtfW9RI",
      repoUrl: "https://github.com/FrancoGL20/Animacion-con-C-desde-Celular",
      screenshots: [
        "https://images.unsplash.com/photo-1617791160505-6f00504e3519?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1470&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Captura de movimiento del celular mediante sensores Flutter",
          "Comunicación en tiempo real con un servidor C vía sockets",
          "Renderizado de animaciones 3D en la computadora",
          "Configuración de IP y puerto para conexión remota"
        ]
      }
    },
    {
      title: "Tienda Online iOS 🛒",
      problem: "Aplicación de comercio electrónico desarrollada en Swift para iOS.",
      solution: "Backend en Node.js (Glitch) y base de datos PostgreSQL en ElephantSQL.",
      tech: "Swift, Node.js, PostgreSQL, Glitch",
      result: "Experiencia de compra completa.",
      image: "https://muchosnegociosrentables.com/wp-content/uploads/2020/05/monta-tu-propia-tienda-online.jpg",      repoUrl: "https://github.com/bryanvrgsc/swift_proyecto_final_apps",
      presentationUrl: "docs/ios_store_presentation.pdf",
      screenshots: [
        "https://muchosnegociosrentables.com/wp-content/uploads/2020/05/monta-tu-propia-tienda-online.jpg",
        "https://splitmetrics.com/wp-content/uploads/2017/06/apple-app-store-1-1-1024x498.png",
        "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=1470&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
          "Registro de usuario",
          "Agregar productos al carrito de compras",
          "Realizar compras",
          "Visualizar historial de compras",
          "Revisar y editar perfil de usuario"
        ],
        techStack: [
            "Swift (iOS)",
            "Node.js (Backend en Glitch)",
            "PostgreSQL (ElephantSQL)",
            "Glitch (Hosting)"
        ]
      }
    },
    {
      title: "Calendarización de Citas 📅",
      problem: "App multiplataforma (iOS y Android) para gestión de membresías y acceso físico.",
      solution: "Solución integral con Flutter, Firebase, y QR Scanner, ideal para gestión de servicios y acceso mediante QR.",
      tech: "Flutter, Dart, Firebase, QR Scanner",
      result: "Gestión eficiente de citas y accesos.",
      image: "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1470&auto=format&fit=crop",      repoUrl: "https://github.com/bryanvrgsc/flutter_proyecto_final_apps",
      videoUrl: "https://drive.google.com/file/d/1VYnOJINVIiF5S1bowKk9b6_3pj_YH1JV/preview",
      presentationUrl: "docs/appointment_app_presentation.pdf",
      screenshots: [
        "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=1468&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1595078475328-1ab05d0a6a0e?q=80&w=1374&auto=format&fit=crop"
      ],
      details: {
        currentFeatures: [
           "Autenticación segura con Firebase Auth",
           "Gestión de membresías y servicios",
           "Generación y escaneo de códigos QR de acceso",
           "Calendario de asistencias / registro de entradas y salidas",
           "Interfaz multiplataforma para iOS y Android"
        ],
        techStack: [
            "firebase_auth, cloud_firestore, firebase_core",
            "qr_flutter, qr_code_scanner",
            "syncfusion_flutter_calendar (para calendario de asistencias)",
            "url_launcher",
            "Entre otros utilitarios para manejo de datos y UI"
        ]
      }
    },
    {
      title: "Scripts de Análisis Predictivo",
      problem: "Exceso de stock y compras ineficientes.",
      solution: "Algoritmos en Python para predicción de demanda estacional.",
      tech: "Python, Pandas, Scitkit-learn",
      result: "Optimización de inventario en un 25%.",
      image: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1470&auto=format&fit=crop",
      screenshots: [
        "https://images.unsplash.com/photo-1551033406-611cf9a28f67?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1470&auto=format&fit=crop",
        "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1415&auto=format&fit=crop"
      ]
    }
  ]
};

